### ISSUE TITLE
TypeError: print_js_1.default is not a function

### ISSUE THREAD

**Issue by renjfk** [crabbly/Print.js#304]
When used with webpack and typescript getting the error mentioned on title. Transpiled code appears to be like this:

```javascript
...
print_js_1.default({
   printable: url,
   type: "pdf",
...
```

And it works fine when bundled without `libraryExport: 'default'` config.

**Comment by renjfk** [comment]
#234 appears to be breaking what has been achieved with #230

**Comment by renjfk** [comment]
Nevermind, appears to be already discussed on #121 and resolves with #293.

**Comment by crabbly** [comment]
@renjfk 
Hey Soner, 
Thank you for the feedback. I couldn't test the interface change, that's why it wasn't merged yet.
Could you take a look at the changes and give me your feedback?
https://github.com/crabbly/Print.js/pull/293/commits/9732c7c3b2daeb8c04408aa6af5a26a7677a876d
It would be nice to fix this issue.
Thank you.

**Comment by renjfk** [comment]
Yup, I've already put that in work with local declarations and I can confirm working perfectly fine.

**Comment by crabbly** [comment]
Sweet! I'll go ahead and merge this. 
Will keep this this issue opened until we release the new changes. 
Thank you for helping! :)

**Comment by crabbly** [comment]
@renjfk @asfernandes @samtsai
The interface changes were released but I'm still getting the same error on this codesandbox:
https://codesandbox.io/s/wq7pplxznl

It works if I don't import the actual exported function and use the exposed global `window.printJS` function. 

I don't use Typescript, therefore I'm still not familiar with its syntax. But it sounds to me that the interface should be informing us that the `printJS` export is a function. Right now, we declare the namespace and function with the same `printJS` name. Could that be the problem? 

I need to eventually get into Typescript, but in the meantime, do you guys have any thoughts on this?
Thank you.

**Comment by crabbly** [comment]
FYI: https://github.com/crabbly/Print.js/issues/57#issuecomment-492842218

**Comment by asfernandes** [comment]
@crabbly with latest version it should be:

```ts
import printJS = require('print-js');
```

and if necessary:

```ts
import { Configuration } from 'print-js';
```

**Comment by crabbly** [comment]
Hey @asfernandes, when would we need to import the configuration?

**Comment by asfernandes** [comment]
Only if you need/want to explicitely declare a variable to its type.

So, it's possible import only printJS and:

```ts
printJS({ .... });
```

or import also Configuration:

```ts
const config: Configuration = { .... };
printJS(config);
```

**Comment by crabbly** [comment]
@asfernandes Thank you, Adriano.

Is there any way we could use es6 modules instead?

For ref: https://codesandbox.io/s/wq7pplxznl

**Comment by asfernandes** [comment]
Do you mean the function is already exported as es6 module?

**Comment by crabbly** [comment]
Yes. The actual `printJS` function is exported here:
https://github.com/crabbly/Print.js/blob/master/src/index.js#L10

But in the interface, I don't know if it matches. 
https://github.com/crabbly/Print.js/blob/master/src/index.d.ts#L41
Again, I don't know much about Typescript yet, therefore, relying heavily on your guys to get this properly setup in the library.

The idea is to support es6 module import in the TypeScript interface, so that this wouldn't create an undefined error:

`import printJS from 'print-js'`

Thanks again for all the help.

Here is a codesandbox showing the es6 import working fine without TypeScript:
https://codesandbox.io/s/x2yrj0kwww

**Comment by buaziz** [comment]
just use 

```typescript
import * as printJs from 'print-js'
```
